"use client";

import { useState } from "react";
import {
  Check,
  X,
  RotateCcw,
  Loader2,
  ListTodo,
  FolderPlus,
  BookMarked,
  FileEdit,
  Database,
  ChevronDown,
  Layers,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import type { ChatToolCall } from "@/app/(app)/advisor/_lib/types";

interface ToolActionCardProps {
  toolCall: ChatToolCall;
  onApprove?: (toolCall: ChatToolCall) => Promise<void>;
  onReject?: (toolCall: ChatToolCall) => Promise<void>;
  onUndo?: (toolCall: ChatToolCall) => Promise<void>;
  disabled?: boolean;
}

/**
 * Returns an appropriate icon based on the tool name.
 */
function getToolIcon(toolName: string) {
  if (toolName.includes("Task")) return <ListTodo className="size-4 text-primary" />;
  if (toolName.includes("Outline")) return <Layers className="size-4 text-primary" />;
  if (toolName.includes("Box")) return <FolderPlus className="size-4 text-primary" />;
  if (toolName.includes("Note") || toolName.includes("Annotation"))
    return <BookMarked className="size-4 text-primary" />;
  if (toolName.includes("Matrix")) return <FileEdit className="size-4 text-primary" />;
  return <Database className="size-4 text-primary" />;
}

/**
 * Returns a human-friendly Turkish action title.
 */
function getToolTitle(toolName: string) {
  switch (toolName) {
    case "createTask":
      return "Kanban Görevi Oluşturma Talebi";
    case "updateTaskStatus":
      return "Görev Durumu Güncelleme Talebi";
    case "createOutlineSection":
      return "Bölüm Planına Yeni Başlık Ekleme";
    case "updateOutlineSection":
      return "Bölüm Planı Güncelleme";
    case "createBox":
      return "Yeni Araştırma Kutusu Oluşturma";
    case "updateBox":
      return "Araştırma Kutusu Güncelleme";
    case "deleteBox":
      return "Araştırma Kutusu Silme Talebi";
    case "addNote":
      return "Alıntı / Not Ekleme Talebi";
    case "deleteNote":
      return "Not Silme Talebi";
    case "updateSource":
      return "Kütüphane Kaynağı Güncelleme";
    case "deleteSource":
      return "Kütüphane Kaynağı Silme";
    case "updateThesisMatrix":
      return "Tez Matrisi Güncelleme Talebi";
    case "pinAnnotationToOutline":
      return "Alıntıyı Bölüme İğneleme";
    case "unpinAnnotationFromOutline":
      return "Alıntı İğnesini Kaldırma";
    case "linkSourceToOutline":
      return "Kaynağı Bölüme Bağlama";
    case "unlinkSourceFromOutline":
      return "Kaynak Bağını Kaldırma";
    default:
      return "Veritabanı İşlem Talebi";
  }
}

/**
 * Renders an interactive action card for pending, approved, rejected, or undone
 * database mutations generated by the Thesis Advisor agent.
 */
export function ToolActionCard({
  toolCall,
  onApprove,
  onReject,
  onUndo,
  disabled = false,
}: ToolActionCardProps) {
  const [isProcessing, setIsProcessing] = useState(false);
  const [isDetailsExpanded, setIsDetailsExpanded] = useState(false);

  const handleApprove = async () => {
    if (!onApprove || isProcessing) return;
    setIsProcessing(true);
    try {
      await onApprove(toolCall);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleReject = async () => {
    if (!onReject || isProcessing) return;
    setIsProcessing(true);
    try {
      await onReject(toolCall);
    } finally {
      setIsProcessing(false);
    }
  };

  const handleUndo = async () => {
    if (!onUndo || isProcessing) return;
    setIsProcessing(true);
    try {
      await onUndo(toolCall);
    } finally {
      setIsProcessing(false);
    }
  };

  const isPending = toolCall.status === "pending";
  const isApproved = toolCall.status === "approved";
  const isRejected = toolCall.status === "rejected";
  const isUndone = toolCall.status === "undone";

  return (
    <div className="rounded-lg border border-border bg-card/90 p-3.5 my-2 shadow-xs transition-all">
      {/* Header */}
      <div className="flex items-center justify-between gap-2 pb-2 border-b border-border/40">
        <div className="flex items-center gap-2 min-w-0">
          <div className="p-1.5 rounded-md bg-primary/10 border border-primary/20 shrink-0">
            {getToolIcon(toolCall.name)}
          </div>
          <span className="font-serif text-xs font-semibold text-foreground truncate">
            {getToolTitle(toolCall.name)}
          </span>
        </div>

        {/* Status Badge */}
        <div>
          {isPending && (
            <span className="px-2 py-0.5 rounded-md text-[10px] font-medium bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">
              Onay Bekliyor
            </span>
          )}
          {isApproved && (
            <span className="px-2 py-0.5 rounded-md text-[10px] font-medium bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20 flex items-center gap-1">
              <Check className="size-3" />
              Uygulandı
            </span>
          )}
          {isRejected && (
            <span className="px-2 py-0.5 rounded-md text-[10px] font-medium bg-muted text-muted-foreground border border-border">
              Reddedildi
            </span>
          )}
          {isUndone && (
            <span className="px-2 py-0.5 rounded-md text-[10px] font-medium bg-muted text-muted-foreground border border-border">
              Geri Alındı
            </span>
          )}
        </div>
      </div>

      {/* Body: Explanation */}
      <div className="py-2 text-xs text-foreground/90 leading-relaxed font-sans">
        {toolCall.explanation}
      </div>

      {/* Expandable Parameter Details */}
      {toolCall.args && Object.keys(toolCall.args).length > 0 && (
        <div className="pt-1 pb-2">
          <button
            type="button"
            onClick={() => setIsDetailsExpanded((prev) => !prev)}
            className="flex items-center gap-1 text-[11px] font-medium text-muted-foreground hover:text-foreground transition-colors cursor-pointer select-none"
          >
            <ChevronDown
              className={`size-3 transition-transform duration-200 ${
                isDetailsExpanded ? "rotate-180" : ""
              }`}
            />
            <span>{isDetailsExpanded ? "Parametreleri Gizle" : "İşlem Detayları"}</span>
          </button>

          {isDetailsExpanded && (
            <div className="mt-1.5 p-2 rounded-md bg-muted/40 border border-border/50 font-mono text-[11px] space-y-1 overflow-x-auto text-foreground/80">
              {Object.entries(toolCall.args).map(([key, val]) => (
                <div key={key} className="flex gap-2">
                  <span className="text-muted-foreground">{key}:</span>
                  <span className="font-sans font-medium text-foreground">
                    {typeof val === "object" ? JSON.stringify(val) : String(val)}
                  </span>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex items-center justify-end gap-2 pt-2 border-t border-border/40">
        {isPending && (
          <>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={handleReject}
              disabled={disabled || isProcessing}
              className="h-7 text-xs px-2.5 rounded-md border-border text-muted-foreground hover:text-foreground hover:bg-muted/40 cursor-pointer transition-colors"
            >
              <X className="size-3.5 mr-1" />
              <span>Reddet</span>
            </Button>
            <Button
              type="button"
              size="sm"
              onClick={handleApprove}
              disabled={disabled || isProcessing}
              className="h-7 text-xs px-3 rounded-md bg-primary text-primary-foreground hover:bg-primary/90 font-medium cursor-pointer transition-colors"
            >
              {isProcessing ? (
                <Loader2 className="size-3.5 mr-1 animate-spin" />
              ) : (
                <Check className="size-3.5 mr-1" />
              )}
              <span>Onayla ve Uygula</span>
            </Button>
          </>
        )}

        {isApproved && (
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={handleUndo}
            disabled={disabled || isProcessing}
            className="h-7 text-xs px-2.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted/40 cursor-pointer transition-colors"
            title="Yapılan işlemi geri al"
          >
            {isProcessing ? (
              <Loader2 className="size-3.5 mr-1 animate-spin" />
            ) : (
              <RotateCcw className="size-3.5 mr-1" />
            )}
            <span>Geri Al</span>
          </Button>
        )}
      </div>
    </div>
  );
}
