import { z } from "zod";
import { FLASH_LITE_31, GEMINI_SEED } from "@/lib/constants";
import {
  generateGeminiStructuredContent,
  type JsonSchema,
} from "@/services/ai";
import type { Logger } from "@/lib/logger";
import type { PositioningMatrixInput } from "./validation";

/**
 * Zod schema for TR+EN search queries (4 alternatives per language) generated by Gemini.
 */
export const generatedQueriesSchema = z.object({
  subjectTr_alt1: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 1 — problem mekanizması)",
    ),
  subjectTr_alt2: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 2 — aktörler/kurumlar)",
    ),
  subjectTr_alt3: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 3 — coğrafi/tarihsel bağlam)",
    ),
  subjectTr_alt4: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 4 — geniş akademik eşanlamlı)",
    ),
  subjectEn_alt1: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 1 — problem mechanism)",
    ),
  subjectEn_alt2: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 2 — actors/institutions)",
    ),
  subjectEn_alt3: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 3 — geographic/temporal context)",
    ),
  subjectEn_alt4: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 4 — broad academic synonym)",
    ),
});

/** Inferred type for the generated positioning search queries. */
export type GeneratedQueries = z.infer<typeof generatedQueriesSchema>;

/** JSON Schema for Gemini structured outputs. */
export const generatedQueriesJsonSchema: JsonSchema = {
  type: "object",
  properties: {
    subjectTr_alt1: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 1 — problem mekanizması)",
    },
    subjectTr_alt2: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 2 — aktörler/kurumlar)",
    },
    subjectTr_alt3: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 3 — coğrafi/tarihsel bağlam)",
    },
    subjectTr_alt4: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 4 — geniş akademik eşanlamlı)",
    },
    subjectEn_alt1: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 1 — problem mechanism)",
    },
    subjectEn_alt2: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 2 — actors/institutions)",
    },
    subjectEn_alt3: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 3 — geographic/temporal context)",
    },
    subjectEn_alt4: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 4 — broad academic synonym)",
    },
  },
  required: [
    "subjectTr_alt1",
    "subjectTr_alt2",
    "subjectTr_alt3",
    "subjectTr_alt4",
    "subjectEn_alt1",
    "subjectEn_alt2",
    "subjectEn_alt3",
    "subjectEn_alt4",
  ],
  additionalProperties: false,
};

/**
 * Removes boolean operators and punctuation syntax for strict Meilisearch compatibility.
 *
 * @param rawQuery - The raw query string to sanitize.
 * @returns The cleaned query string safe for Meilisearch.
 */
export function sanitizeMeiliQuery(rawQuery: string): string {
  if (!rawQuery) return "";
  return rawQuery
    .replace(/\b(OR|AND|NOT)\b/gi, " ")
    .replace(/[+*?:^~={}[\]()"\\]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

import { buildPositioningQueriesPromptPayload } from "./prompts/queries.prompt";

/**
 * Generates 8 sanitized TR+EN search queries from the positioning matrix via Gemini.
 *
 * @param input - The validated positioning matrix input.
 * @param logger - Optional structured logger for pipeline events.
 * @returns The sanitized generated queries object.
 */
export async function generatePositioningQueries(
  input: PositioningMatrixInput,
  logger?: Logger,
): Promise<GeneratedQueries> {
  const payload = buildPositioningQueriesPromptPayload(input);

  const result = await generateGeminiStructuredContent<GeneratedQueries>(
    FLASH_LITE_31,
    payload.systemInstruction,
    payload.userPrompt,
    generatedQueriesJsonSchema,
    logger,
    {
      zodSchema: generatedQueriesSchema,
      payloadStage: "generate_positioning_queries",
      seed: GEMINI_SEED,
      thesisMatrix: input,
    },
  );

  return {
    subjectTr_alt1: sanitizeMeiliQuery(result.subjectTr_alt1),
    subjectTr_alt2: sanitizeMeiliQuery(result.subjectTr_alt2),
    subjectTr_alt3: sanitizeMeiliQuery(result.subjectTr_alt3),
    subjectTr_alt4: sanitizeMeiliQuery(result.subjectTr_alt4),
    subjectEn_alt1: sanitizeMeiliQuery(result.subjectEn_alt1),
    subjectEn_alt2: sanitizeMeiliQuery(result.subjectEn_alt2),
    subjectEn_alt3: sanitizeMeiliQuery(result.subjectEn_alt3),
    subjectEn_alt4: sanitizeMeiliQuery(result.subjectEn_alt4),
  };
}
