import { redirect } from "next/navigation";
import { getProfile } from "@/lib/session";
import { BoxesContainer } from "./_components/boxes-container";
import { OnboardingStepHeader } from "../_components/onboarding-step-header";
import { fetchBoxesWithFullShape } from "@/app/(onboarding)/onboarding/_services/fetch-actions";

/**
 * Onboarding step 4: subject boxes page that verifies auth and renders the boxes.
 * Boxes are pre-generated by proceedFromOutline with loading overlay.
 *
 * @returns The subject boxes page markup.
 */
export default async function OnboardingBoxesPage() {
  const profile = await getProfile();

  if (profile.onboardingCompleted) {
    redirect("/dashboard");
  }

  const boxes = await fetchBoxesWithFullShape();
  if (!boxes || boxes.length === 0) {
    redirect("/onboarding/outline");
  }

  return (
    <div className="flex flex-col items-center justify-center p-4 pt-10 pb-4">
      <div className="flex w-full max-w-5xl flex-col items-center space-y-4">
        <OnboardingStepHeader
          title="Konu Kutuları"
          description="Tez matrisinizin çözümlenmesiyle oluşturulan konu kutularını inceleyin ve onaylayın."
        />

        <BoxesContainer />
      </div>
    </div>
  );
}
