import { z } from "zod";
import { FLASH_LITE_31, GEMINI_SEED } from "@/lib/constants";
import {
  generateStructuredContent,
  type JsonSchema,
} from "@/lib/services/gemini";
import type { Logger } from "@/lib/logger";
import type { PositioningMatrixInput } from "../_lib/validation";

/** Zod schema for 3-tier positioning search queries generated by Gemini. */
export const generatedQueriesSchema = z.object({
  directQuery: z
    .string()
    .min(3)
    .describe(
      "Araştırmanın öz nesnesini, aktörlerini ve zaman/mekan bağlamını hedefleyen meilisearch uyumlu ana sorgu terimleri",
    ),
  expandedQuery: z
    .string()
    .min(3)
    .describe(
      "Genişletilmiş politik, stratejik ve söylemsel dönüşüm kavramlarını içeren meilisearch uyumlu terimler",
    ),
  conceptualQuery: z
    .string()
    .min(3)
    .describe("Kuramsal çerçeve, metodoloji ve analitik kavram terimleri"),
});

/** Inferred TypeScript type for generated 3-tier positioning queries. */
export type GeneratedQueries = z.infer<typeof generatedQueriesSchema>;

/** JSON Schema specification passed to Gemini structured outputs. */
export const generatedQueriesJsonSchema: JsonSchema = {
  type: "object",
  properties: {
    directQuery: {
      type: "string",
      description:
        "Araştırmanın öz nesnesini, aktörlerini ve zaman/mekan bağlamını hedefleyen meilisearch uyumlu ana sorgu terimleri",
    },
    expandedQuery: {
      type: "string",
      description:
        "Genişletilmiş politik, stratejik ve söylemsel dönüşüm kavramlarını içeren meilisearch uyumlu terimler",
    },
    conceptualQuery: {
      type: "string",
      description: "Kuramsal çerçeve, metodoloji ve analitik kavram terimleri",
    },
  },
  required: ["directQuery", "expandedQuery", "conceptualQuery"],
  additionalProperties: false,
};

/**
 * Sanitizes a generated query string for strict Meilisearch full-text compatibility.
 * Removes boolean operators (OR, AND, NOT) and punctuation syntax characters that cause
 * unexpected literal term matching in Meilisearch.
 *
 * @param rawQuery - Raw query string generated by LLM.
 * @returns Cleaned query string optimized for Meilisearch keyword matching.
 */
export function sanitizeMeiliQuery(rawQuery: string): string {
  if (!rawQuery) return "";
  return rawQuery
    .replace(/\b(OR|AND|NOT)\b/gi, " ")
    .replace(/[+*?:^~={}\[\]()"\\]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

import {
  POSITIONING_QUERIES_SYSTEM_INSTRUCTION,
  buildPositioningQueriesUserPrompt,
} from "@/lib/prompts";

/**
 * Generates 3-tier academic search queries (direct, expanded, conceptual) from user's
 * 5-field positioning matrix using Gemini Flash-Lite.
 *
 * @param input - The validated 5-field positioning matrix input.
 * @param logger - Optional Logger instance for structured telemetry.
 * @returns Object containing directQuery, expandedQuery, and conceptualQuery.
 */
export async function generatePositioningQueries(
  input: PositioningMatrixInput,
  logger?: Logger,
): Promise<GeneratedQueries> {
  const userPrompt = buildPositioningQueriesUserPrompt(input);

  const result = await generateStructuredContent<GeneratedQueries>(
    FLASH_LITE_31,
    POSITIONING_QUERIES_SYSTEM_INSTRUCTION,
    userPrompt,
    generatedQueriesJsonSchema,
    logger,
    {
      zodSchema: generatedQueriesSchema,
      payloadStage: "generate_positioning_queries",
      seed: GEMINI_SEED,
      thesisMatrix: input,
    },
  );

  return {
    directQuery: sanitizeMeiliQuery(result.directQuery),
    expandedQuery: sanitizeMeiliQuery(result.expandedQuery),
    conceptualQuery: sanitizeMeiliQuery(result.conceptualQuery),
  };
}
