import { z } from "zod";
import { FLASH_LITE_31, GEMINI_SEED } from "@/lib/constants";
import {
  generateStructuredContent,
  type JsonSchema,
} from "@/lib/services/gemini";
import type { Logger } from "@/lib/logger";
import type { PositioningMatrixInput } from "../_lib/validation";

/**
 * Zod schema for single-field × TR+EN positioning search queries generated by Gemini.
 * Fields: subject (araştırma problemi — aktörler ve ampirik bağlam dahil).
 * Each language has 4 alternative queries (alt1–alt4).
 *
 * ANALYSIS_ACTORS has been removed — actors are now integral to subjectProblem.
 * To maintain Meilisearch coverage breadth, 4 alternatives per language are used
 * (problem angle, actor angle, geographic/temporal angle, mechanism angle).
 */
export const generatedQueriesSchema = z.object({
  subjectTr_alt1: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 1 — problem mekanizması)",
    ),
  subjectTr_alt2: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 2 — aktörler/kurumlar)",
    ),
  subjectTr_alt3: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 3 — coğrafi/tarihsel bağlam)",
    ),
  subjectTr_alt4: z
    .string()
    .min(2)
    .describe(
      "Araştırma problemi/odağı için 2-4 kelimelik Türkçe sorgu (alternatif 4 — geniş akademik eşanlamlı)",
    ),
  subjectEn_alt1: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 1 — problem mechanism)",
    ),
  subjectEn_alt2: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 2 — actors/institutions)",
    ),
  subjectEn_alt3: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 3 — geographic/temporal context)",
    ),
  subjectEn_alt4: z
    .string()
    .min(2)
    .describe(
      "Research problem/focus — 2-4 word English query (alternative 4 — broad academic synonym)",
    ),
});

/** Inferred TypeScript type for generated single-field × TR+EN positioning queries. */
export type GeneratedQueries = z.infer<typeof generatedQueriesSchema>;

/** JSON Schema specification passed to Gemini structured outputs. */
export const generatedQueriesJsonSchema: JsonSchema = {
  type: "object",
  properties: {
    subjectTr_alt1: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 1 — problem mekanizması)",
    },
    subjectTr_alt2: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 2 — aktörler/kurumlar)",
    },
    subjectTr_alt3: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 3 — coğrafi/tarihsel bağlam)",
    },
    subjectTr_alt4: {
      type: "string",
      description:
        "Araştırma problemi ve odağı için 2-4 kelimelik Türkçe Meilisearch sorgusu (alternatif 4 — geniş akademik eşanlamlı)",
    },
    subjectEn_alt1: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 1 — problem mechanism)",
    },
    subjectEn_alt2: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 2 — actors/institutions)",
    },
    subjectEn_alt3: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 3 — geographic/temporal context)",
    },
    subjectEn_alt4: {
      type: "string",
      description:
        "Research problem and focus — 2-4 word English Meilisearch query (alternative 4 — broad academic synonym)",
    },
  },
  required: [
    "subjectTr_alt1",
    "subjectTr_alt2",
    "subjectTr_alt3",
    "subjectTr_alt4",
    "subjectEn_alt1",
    "subjectEn_alt2",
    "subjectEn_alt3",
    "subjectEn_alt4",
  ],
  additionalProperties: false,
};

/**
 * Sanitizes a generated query string for strict Meilisearch full-text compatibility.
 * Removes boolean operators (OR, AND, NOT) and punctuation syntax characters that cause
 * unexpected literal term matching in Meilisearch.
 *
 * @param rawQuery - Raw query string generated by LLM.
 * @returns Cleaned query string optimized for Meilisearch keyword matching.
 */
export function sanitizeMeiliQuery(rawQuery: string): string {
  if (!rawQuery) return "";
  return rawQuery
    .replace(/\b(OR|AND|NOT)\b/gi, " ")
    .replace(/[+*?:^~={}[\]()"\\]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

import {
  POSITIONING_QUERIES_SYSTEM_INSTRUCTION,
  buildPositioningQueriesUserPrompt,
} from "@/lib/prompts";

/**
 * Generates 8 short academic search queries (single field × TR + EN × 4 alternatives)
 * from the user's 3-field positioning matrix using Gemini Flash-Lite.
 *
 * Fields used: subjectProblem (araştırma problemi — aktörler ve ampirik bağlam dahil).
 * Methodology and theoreticalFramework are intentionally excluded.
 *
 * @param input - The validated 3-field positioning matrix input.
 * @param logger - Optional Logger instance for structured telemetry.
 * @returns Object containing 8 sanitized Meilisearch queries.
 */
export async function generatePositioningQueries(
  input: PositioningMatrixInput,
  logger?: Logger,
): Promise<GeneratedQueries> {
  const userPrompt = buildPositioningQueriesUserPrompt(input);

  const result = await generateStructuredContent<GeneratedQueries>(
    FLASH_LITE_31,
    POSITIONING_QUERIES_SYSTEM_INSTRUCTION,
    userPrompt,
    generatedQueriesJsonSchema,
    logger,
    {
      zodSchema: generatedQueriesSchema,
      payloadStage: "generate_positioning_queries",
      seed: GEMINI_SEED,
      thesisMatrix: input,
    },
  );

  return {
    subjectTr_alt1: sanitizeMeiliQuery(result.subjectTr_alt1),
    subjectTr_alt2: sanitizeMeiliQuery(result.subjectTr_alt2),
    subjectTr_alt3: sanitizeMeiliQuery(result.subjectTr_alt3),
    subjectTr_alt4: sanitizeMeiliQuery(result.subjectTr_alt4),
    subjectEn_alt1: sanitizeMeiliQuery(result.subjectEn_alt1),
    subjectEn_alt2: sanitizeMeiliQuery(result.subjectEn_alt2),
    subjectEn_alt3: sanitizeMeiliQuery(result.subjectEn_alt3),
    subjectEn_alt4: sanitizeMeiliQuery(result.subjectEn_alt4),
  };
}
