import { z } from "zod";
import { FLASH_LITE_31, GEMINI_SEED } from "@/lib/constants";
import {
  generateStructuredContent,
  type JsonSchema,
} from "@/lib/services/gemini";
import type { Logger } from "@/lib/logger";
import type { PositioningMatrixInput } from "../_lib/validation";

/**
 * Zod schema for 3-field × TR+EN positioning search queries generated by Gemini.
 * Fields: subject (odak/problem), theory (teorik çerçeve), actors (analiz birimi/aktörler).
 * Each query is exactly 3 keywords for optimal Meilisearch BM25 precision.
 */
export const generatedQueriesSchema = z.object({
  subjectTr: z
    .string()
    .min(3)
    .describe("Çalışmanın odağı/problemi için tam 3 kelimelik Türkçe sorgu"),
  subjectEn: z
    .string()
    .min(3)
    .describe("Çalışmanın odağı/problemi için tam 3 kelimelik İngilizce sorgu"),
  theoryTr: z
    .string()
    .min(3)
    .describe("Teorik çerçeve için tam 3 kelimelik Türkçe sorgu"),
  theoryEn: z
    .string()
    .min(3)
    .describe("Teorik çerçeve için tam 3 kelimelik İngilizce sorgu"),
  actorsTr: z
    .string()
    .min(3)
    .describe("Analiz birimi/aktörler için tam 3 kelimelik Türkçe sorgu"),
  actorsEn: z
    .string()
    .min(3)
    .describe("Analiz birimi/aktörler için tam 3 kelimelik İngilizce sorgu"),
});

/** Inferred TypeScript type for generated 3-field × TR+EN positioning queries. */
export type GeneratedQueries = z.infer<typeof generatedQueriesSchema>;

/** JSON Schema specification passed to Gemini structured outputs. */
export const generatedQueriesJsonSchema: JsonSchema = {
  type: "object",
  properties: {
    subjectTr: {
      type: "string",
      description:
        "Çalışmanın odağı ve problemi için tam 3 kelimelik Türkçe Meilisearch sorgusu",
    },
    subjectEn: {
      type: "string",
      description:
        "Çalışmanın odağı ve problemi için tam 3 kelimelik İngilizce Meilisearch sorgusu",
    },
    theoryTr: {
      type: "string",
      description:
        "Teorik ve kavramsal çerçeve için tam 3 kelimelik Türkçe Meilisearch sorgusu",
    },
    theoryEn: {
      type: "string",
      description:
        "Teorik ve kavramsal çerçeve için tam 3 kelimelik İngilizce Meilisearch sorgusu",
    },
    actorsTr: {
      type: "string",
      description:
        "Analiz birimi ve aktörler için tam 3 kelimelik Türkçe Meilisearch sorgusu",
    },
    actorsEn: {
      type: "string",
      description:
        "Analiz birimi ve aktörler için tam 3 kelimelik İngilizce Meilisearch sorgusu",
    },
  },
  required: [
    "subjectTr",
    "subjectEn",
    "theoryTr",
    "theoryEn",
    "actorsTr",
    "actorsEn",
  ],
  additionalProperties: false,
};

/**
 * Sanitizes a generated query string for strict Meilisearch full-text compatibility.
 * Removes boolean operators (OR, AND, NOT) and punctuation syntax characters that cause
 * unexpected literal term matching in Meilisearch.
 *
 * @param rawQuery - Raw query string generated by LLM.
 * @returns Cleaned query string optimized for Meilisearch keyword matching.
 */
export function sanitizeMeiliQuery(rawQuery: string): string {
  if (!rawQuery) return "";
  return rawQuery
    .replace(/\b(OR|AND|NOT)\b/gi, " ")
    .replace(/[+*?:^~={}[\]()"\\]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

import {
  POSITIONING_QUERIES_SYSTEM_INSTRUCTION,
  buildPositioningQueriesUserPrompt,
} from "@/lib/prompts";

/**
 * Generates 6 short academic search queries (3 matrix fields × TR + EN, each exactly 3 keywords)
 * from the user's 4-field positioning matrix using Gemini Flash-Lite.
 *
 * Fields used: subjectProblem, theoreticalFramework, analysisActors.
 * Methodology is intentionally excluded to reduce noise.
 *
 * @param input - The validated 4-field positioning matrix input.
 * @param logger - Optional Logger instance for structured telemetry.
 * @returns Object containing 6 sanitized 3-keyword Meilisearch queries.
 */
export async function generatePositioningQueries(
  input: PositioningMatrixInput,
  logger?: Logger,
): Promise<GeneratedQueries> {
  const userPrompt = buildPositioningQueriesUserPrompt(input);

  const result = await generateStructuredContent<GeneratedQueries>(
    FLASH_LITE_31,
    POSITIONING_QUERIES_SYSTEM_INSTRUCTION,
    userPrompt,
    generatedQueriesJsonSchema,
    logger,
    {
      zodSchema: generatedQueriesSchema,
      payloadStage: "generate_positioning_queries",
      seed: GEMINI_SEED,
      thesisMatrix: input,
    },
  );

  return {
    subjectTr: sanitizeMeiliQuery(result.subjectTr),
    subjectEn: sanitizeMeiliQuery(result.subjectEn),
    theoryTr: sanitizeMeiliQuery(result.theoryTr),
    theoryEn: sanitizeMeiliQuery(result.theoryEn),
    actorsTr: sanitizeMeiliQuery(result.actorsTr),
    actorsEn: sanitizeMeiliQuery(result.actorsEn),
  };
}
