import { redirect } from "next/navigation";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { matrices, outlines } from "@/db/schema";
import { getProfile } from "@/lib/session";
import { OutlineContainer } from "./_components/outline-container";
import { StartOverButton } from "../_components/start-over-button";

/**
 * Renders the outline onboarding step for the authenticated user.
 * Outline is expected to be pre-generated by proceedFromBoxes with loading overlay.
 *
 * @returns The outline page UI.
 */
export default async function OutlinePage() {
  const profile = await getProfile();

  const [matrix] = await db
    .select({ id: matrices.id })
    .from(matrices)
    .where(eq(matrices.userId, profile.id));

  if (!matrix) {
    redirect("/onboarding/matrix");
  }

  const existingOutlines = await db
    .select()
    .from(outlines)
    .where(eq(outlines.matrixId, matrix.id))
    .orderBy(outlines.sortOrder);

  if (existingOutlines.length === 0) {
    redirect("/onboarding/boxes");
  }

  return buildOutlinePage(existingOutlines, matrix.id);
}

/**
 * Builds the outline page from outline rows.
 *
 * @param outlineRows - The outline rows from the database.
 * @param _matrixId - The thesis matrix id (unused, reserved for future).
 * @returns The outline page UI.
 */
function buildOutlinePage(
  outlineRows: Array<{
    id: number;
    matrixId: number;
    parentId: number | null;
    title: string;
    description: string | null;
    sortOrder: number;
    academicField: string | null;
  }>,
  _matrixId: number,
) {
  const parentRows = outlineRows.filter((r) => r.parentId === null);
  const childMap = new Map<number, typeof outlineRows>();
  for (const row of outlineRows) {
    if (row.parentId !== null) {
      const list = childMap.get(row.parentId) ?? [];
      list.push(row);
      childMap.set(row.parentId, list);
    }
  }

  const sections = parentRows.map((parent) => ({
    title: parent.title,
    description: parent.description ?? "",
    sortOrder: parent.sortOrder,
    subSections: (childMap.get(parent.id) ?? []).map((child) => ({
      title: child.title,
      description: child.description ?? "",
      sortOrder: child.sortOrder,
    })),
  }));

  return (
    <div className="flex flex-col items-center justify-center p-4 pt-10 pb-4">
      <div className="mx-auto flex w-full max-w-5xl flex-col items-center space-y-4">
        <div className="flex w-full flex-col sm:flex-row justify-between items-start sm:items-center gap-4 pb-6 border-b border-border">
          <div className="flex flex-col space-y-1 text-left">
            <h1 className="font-serif text-2xl font-bold tracking-tight text-foreground">
              Tez Planı
            </h1>
            <p className="text-sm leading-relaxed text-muted-foreground">
              Tez matrisinizden otomatik oluşturulan bölüm yapısı.
            </p>
          </div>
          <div className="flex items-center self-end sm:self-center">
            <StartOverButton />
          </div>
        </div>

        <OutlineContainer sections={sections} />
      </div>
    </div>
  );
}
